# Scinum Tutorial

Initialize scinum objects by passing numbers and respective uncertainty pairs OR a list of values with the same uncertainty. Will expand dimenions if not of same size. Can use operations normally to find number uncertainty pairs.

In [6]:
from scinum import scinum
import numpy as np

count = scinum([[1, 0.1], [2, 0.2], [3, 0.3], [4, 0.4]])
rad = scinum([2, 2], uncer = 0)

print(count*rad*0.002)

Warning, arrays are not the same size, expanding dims...
[[0.004  0.0004]
 [0.008  0.0008]
 [0.012  0.0012]
 [0.016  0.0016]]


Output a table in LaTex format.

In [7]:
scinum.table([count, count*rad*0.002], ["Count", "Angular Velocity"], fmt = "latex")

Warning, arrays are not the same size, expanding dims...
\begin{tabular}{ll}
\hline
 Count     & Angular Velocity   \\
\hline
 1.0 (0.1) & 0.0040 (0.0004)    \\
 2.0 (0.2) & 0.0080 (0.0008)    \\
 3.0 (0.3) & 0.012 (0.001)      \\
 4.0 (0.4) & 0.016 (0.002)      \\
\hline
\end{tabular}


Apply a function 's' to a given variable and output in a Markdown table.

In [8]:
data = [1.0,2.0345,3.0345,4.0345,5.0345]
data2 = [10.1,23.1,30.1,40.1,50.1]

p = scinum(data, uncer = 0.004)
q = scinum(data2, uncer = 2)
r = scinum(data2, uncer = 2)

def s(x):
    return np.sin(x) + x 

r = r.func(s)

scinum.table([p,q,r], ["data p", "data q", "data r"], fmt = "github")

| data p        | data q   | data r     |
|---------------|----------|------------|
| 1.000 (0.004) | 10 (2)   | 9.5 (0.4)  |
| 2.034 (0.004) | 23 (2)   | 22 (1)     |
| 3.034 (0.004) | 30 (2)   | 29 (2)     |
| 4.035 (0.004) | 40 (2)   | 40.8 (0.5) |
| 5.034 (0.004) | 50 (2)   | 49 (3)     |


Propagate error through a function of many uncertain values.

In [5]:
def test(x,y,z):
    return np.exp(z)*np.sin(y)*x**2

a = scinum([1, 3], uncer = 0.5)
b = scinum([2, 4], uncer = 0.1)
c = scinum([3, 3], uncer = 0.64)

print(scinum.f(test, a, b, c))

[[  18.26372704   21.70001267]
 [-136.80706017   99.42505909]]


Using standard operators or more compex functions is equivalent.

In [8]:
a = scinum([1], uncer = 0.5)
b = scinum([2], uncer = 0.1)
c = scinum([3], uncer = 0.64)

print(a+b+c)
x = a+b
print(x+c)

def k(x,y,z):
    return x + y + z

print(scinum.f(k, a, b, c))

[[6.        0.8182909]]
[[6.        0.8182909]]
[[6.        0.8182909]]
