In [3]:
count = scinum([1,2,3,4,5], 0)
rad = scinum([2], uncer = 0.5)

print(count*rad*0.002)

scinum.table([count, count*rad*0.002], ["Count", "Angular Velocity"], fmt = "latex")

Warning, arrays are not the same size, expanding dims...
[[0.004 0.001]
 [0.008 0.002]
 [0.012 0.003]
 [0.016 0.004]
 [0.02  0.005]]
Warning, arrays are not the same size, expanding dims...
\begin{tabular}{rl}
\hline
   Count & Angular Velocity   \\
\hline
       1 & 0.004 (0.001)      \\
       2 & 0.008 (0.002)      \\
       3 & 0.012 (0.003)      \\
       4 & 0.016 (0.004)      \\
       5 & 0.020 (0.005)      \\
\hline
\end{tabular}


In [4]:
data = [1.0,2.0345,3.0345,4.0345,5.0345]
data2 = [10.1,23.1,30.1,40.1,50.1]

p = scinum(data, uncer = 0.004)
q = scinum(data2, uncer = 2)
r = scinum(data2, uncer = 2)

def s(x):
    return np.sin(x) + x 

r = r.func(s)

scinum.table([p,q,r], ["data p", "data q", "data r"])

| data p        | data q   | data r     |
|---------------|----------|------------|
| 1.000 (0.004) | 10 (2)   | 9.5 (0.4)  |
| 2.034 (0.004) | 23 (2)   | 22 (1)     |
| 3.034 (0.004) | 30 (2)   | 29 (2)     |
| 4.035 (0.004) | 40 (2)   | 40.8 (0.5) |
| 5.034 (0.004) | 50 (2)   | 49 (3)     |


In [5]:
def test(x,y,z):
    return np.exp(z)*np.sin(y)*x**2

a = scinum([1, 3], uncer = 0.5)
b = scinum([2, 4], uncer = 0.1)
c = scinum([3, 3], uncer = 0.64)

print(scinum.f(test, a, b, c))

[[  18.26372704   21.70001267]
 [-136.80706017   99.42505909]]


In [8]:
a = scinum([1], uncer = 0.5)
b = scinum([2], uncer = 0.1)
c = scinum([3], uncer = 0.64)

print(a+b+c)
x = a+b
print(x+c)

def k(x,y,z):
    return x + y + z

print(scinum.f(k, a, b, c))

[[6.        0.8182909]]
[[6.        0.8182909]]
[[6.        0.8182909]]
